<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="se7en" failures="1" tests="10" name="myTestProject1.test.registerTest" time="171.288" errors="0" timestamp="06 Dec 2022 18:09:22 GMT" skipped="0">
  <testcase classname="myTestProject1.test.registerTest" name="registerWithoutEmail" time="16.083"/>
  <testcase classname="myTestProject1.test.registerTest" name="registerWithoutUsername" time="10.633"/>
  <testcase classname="myTestProject1.test.registerTest" name="registerWithoutPassword" time="7.426"/>
  <testcase classname="myTestProject1.test.registerTest" name="registerWithWrongConfirmPassword" time="36.325"/>
  <testcase classname="myTestProject1.test.registerTest" name="registerWithoutConfirmPassword" time="6.870"/>
  <testcase classname="myTestProject1.test.registerTest" name="registerWithoutCheckBox" time="5.183"/>
  <testcase classname="myTestProject1.test.registerTest" name="registerWithValidData" time="15.292">
    <failure message="expected [https://turkishemarket.com/] but found [https://turkishemarket.com/users/registration]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [https://turkishemarket.com/] but found [https://turkishemarket.com/users/registration]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at myTestProject1.test.registerTest.registerWithValidData(registerTest.java:74)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
    </failure>
  </testcase> <!-- registerWithValidData -->
  <testcase classname="myTestProject1.test.registerTest" name="registerWithUnAvailableEmail" time="13.201"/>
  <testcase classname="myTestProject1.test.registerTest" name="registerWithInvalidEmail" time="24.659"/>
  <testcase classname="myTestProject1.test.registerTest" name="registerWithInvalidName" time="35.616"/>
</testsuite> <!-- myTestProject1.test.registerTest -->
